import { execFile } from "node:child_process";
import {
  lstat,
  mkdir,
  mkdtemp,
  readFile,
  readdir,
  rename,
  rm,
  symlink,
  unlink,
  writeFile,
} from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, resolve } from "node:path";
import { promisify } from "node:util";
import { afterEach, describe, expect, it } from "vitest";
import {
  inspectHook,
  installHook,
  hookNodeFileSystem,
  uninstallHook,
  type HookDependencies,
} from "../tools/hooks.ts";
import { sha256 } from "../tools/knowledge.ts";

const execFileAsync = promisify(execFile);
const temporaryRoots: string[] = [];
const FRAMEWORK_HOOK =
  '#!/usr/bin/env bash\n# File generated by pre-commit: https://pre-commit.com\n# ID: 138fd403232d2ddd5efb44317e38bf03\nexec pre-commit hook-impl --hook-type=pre-commit --hook-dir "$(dirname "$0")" -- "$@"\n';

async function git(root: string, ...args: string[]): Promise<string> {
  const result = await execFileAsync("git", args, {
    cwd: root,
    encoding: "utf8",
  });
  return result.stdout.trim();
}

async function makeRepository(): Promise<string> {
  const root = await mkdtemp(resolve(tmpdir(), "coffee-chat-hooks-"));
  temporaryRoots.push(root);
  await git(root, "init", "-q");
  await git(root, "config", "user.email", "hooks@example.com");
  await git(root, "config", "user.name", "Hook Test");
  await writeFile(resolve(root, "sentinel.txt"), "sentinel\n");
  await git(root, "add", "sentinel.txt");
  await git(root, "commit", "-qm", "fixture");
  return root;
}

afterEach(async () => {
  await Promise.all(
    temporaryRoots
      .splice(0)
      .map((root) => rm(root, { recursive: true, force: true })),
  );
});

describe("conservative hook inspection", () => {
  it("resolves the actual Git hook path and fingerprints absence in normal and linked worktrees", async () => {
    const root = await makeRepository();
    const inspected = await inspectHook(root);
    expect(inspected).toMatchObject({
      classification: "absent",
      target_path: resolve(
        root,
        await git(root, "rev-parse", "--git-path", "hooks/pre-commit"),
      ),
      fingerprint: { state: "absent" },
    });

    const linked = resolve(dirname(root), `${root.split("/").pop()}-linked`);
    temporaryRoots.push(linked);
    await git(root, "worktree", "add", "-q", "-b", "linked-test", linked);
    const linkedInspection = await inspectHook(linked);
    expect(linkedInspection.target_path).toBe(
      resolve(
        linked,
        await git(linked, "rev-parse", "--git-path", "hooks/pre-commit"),
      ),
    );
    expect(linkedInspection.classification).toBe("absent");
  });

  it("fails safely outside a repository", async () => {
    const root = await mkdtemp(resolve(tmpdir(), "coffee-chat-not-git-"));
    temporaryRoots.push(root);
    await expect(inspectHook(root)).rejects.toMatchObject({
      diagnostic: { code: "hook-path-unavailable" },
    });
  });

  it.each([".custom-hooks", "../external-hooks"])(
    "rejects every configured core.hooksPath in conservative v1: %s",
    async (configured) => {
      const root = await makeRepository();
      await git(root, "config", "core.hooksPath", configured);
      await expect(inspectHook(root)).rejects.toMatchObject({
        diagnostic: { code: "configured-hooks-path" },
      });
      await expect(installHook(root)).rejects.toMatchObject({
        diagnostic: { code: "configured-hooks-path" },
      });
      await expect(uninstallHook(root)).rejects.toMatchObject({
        diagnostic: { code: "configured-hooks-path" },
      });
    },
  );

  it("classifies arbitrary bytes as unmanaged without executing or changing them", async () => {
    const root = await makeRepository();
    const absent = await inspectHook(root);
    const unmanaged = "#!/bin/sh\necho must-not-run > executed.txt\n";
    await mkdir(dirname(absent.target_path), { recursive: true });
    await writeFile(absent.target_path, unmanaged, { mode: 0o755 });
    let processCalls = 0;
    const dependencies: HookDependencies = {
      process: {
        execute: async () => {
          processCalls += 1;
          return { exitCode: 0, stdout: "", stderr: "" };
        },
      },
    };
    expect(await inspectHook(root)).toMatchObject({
      classification: "unmanaged",
    });
    await expect(installHook(root, dependencies)).rejects.toMatchObject({
      diagnostic: { code: "unmanaged-pre-commit-hook" },
    });
    expect(await uninstallHook(root, dependencies)).toMatchObject({
      status: "preserved_unmanaged",
    });
    expect(processCalls).toBe(0);
    expect(await readFile(absent.target_path, "utf8")).toBe(unmanaged);
    await expect(lstat(resolve(root, "executed.txt"))).rejects.toThrow();
  });

  it("rejects marker-spoofed hook bytes with extra commands even when ownership digest is forged", async () => {
    const root = await makeRepository();
    const inspection = await inspectHook(root);
    const spoofed = `${FRAMEWORK_HOOK}echo user-managed-command\n`;
    await writeFile(inspection.target_path, spoofed, { mode: 0o755 });
    await mkdir(dirname(inspection.ownership_path), { recursive: true });
    await writeFile(
      inspection.ownership_path,
      `${JSON.stringify(
        {
          schema_version: "1.0.0",
          owner: "coffee-chat",
          hook_path: inspection.target_path,
          hook_digest: sha256(spoofed),
        },
        null,
        2,
      )}\n`,
    );
    expect((await inspectHook(root)).classification).toBe("unmanaged");
    expect(await uninstallHook(root)).toMatchObject({
      status: "preserved_unmanaged",
    });
    expect(await readFile(inspection.target_path, "utf8")).toBe(spoofed);
  });
});

describe("owned exclusive pre-commit lifecycle", () => {
  it("uses a non-mutating availability probe, then exclusively installs and records target identity", async () => {
    const root = await makeRepository();
    const initial = await inspectHook(root);
    const calls: Array<{
      command: string;
      args: string[];
      env?: Record<string, string>;
    }> = [];
    const result = await installHook(root, {
      process: {
        execute: async (request) => {
          calls.push(request);
          return { exitCode: 0, stdout: "pre-commit 4.0.1\n", stderr: "" };
        },
      },
    });
    expect(result).toMatchObject({
      status: "installed",
      inspection: { classification: "managed" },
    });
    expect(calls).toEqual([
      expect.objectContaining({
        command: "pre-commit",
        args: ["--version"],
      }),
    ]);
    expect(JSON.stringify(calls)).not.toMatch(
      /--no-verify|SKIP|allowlist|gitleaks/,
    );
    const ownership = JSON.parse(
      await readFile(result.inspection.ownership_path, "utf8"),
    ) as {
      owner: string;
      hook_digest: string;
      hook_device: number;
      hook_inode: number;
    };
    expect(ownership.owner).toBe("coffee-chat");
    const fingerprint = result.inspection.fingerprint;
    if (fingerprint.state !== "file") {
      throw new Error(
        `expected file fingerprint, received ${fingerprint.state}`,
      );
    }
    expect(ownership.hook_digest).toBe(fingerprint.digest);
    expect(ownership.hook_device).toBe(fingerprint.device);
    expect(ownership.hook_inode).toBe(fingerprint.inode);
  });

  it("uninstalls only exact Coffee Chat-owned managed bytes and runtime", async () => {
    const root = await makeRepository();
    const initial = await inspectHook(root);
    const installed = await installHook(root, {
      process: {
        execute: async () => ({
          exitCode: 0,
          stdout: "pre-commit 4.0.1\n",
          stderr: "",
        }),
      },
    });
    let processCalls = 0;
    const removal = await uninstallHook(root, {
      process: {
        execute: async () => {
          processCalls += 1;
          return { exitCode: 0, stdout: "", stderr: "" };
        },
      },
    });
    expect(removal.status).toBe("uninstalled");
    expect(processCalls).toBe(0);
    expect((await inspectHook(root)).classification).toBe("absent");
    await expect(lstat(installed.inspection.ownership_path)).rejects.toThrow();
    expect(await readFile(resolve(root, "sentinel.txt"), "utf8")).toBe(
      "sentinel\n",
    );
  });

  it("preserves a hook when bytes or Coffee Chat ownership digest no longer match", async () => {
    const root = await makeRepository();
    const initial = await inspectHook(root);
    const installed = await installHook(root, {
      process: {
        execute: async () => ({
          exitCode: 0,
          stdout: "pre-commit 4.0.1\n",
          stderr: "",
        }),
      },
    });
    await writeFile(
      installed.inspection.target_path,
      `${FRAMEWORK_HOOK}# changed\n`,
    );
    expect((await inspectHook(root)).classification).toBe("unmanaged");
    let processCalls = 0;
    const result = await uninstallHook(root, {
      process: {
        execute: async () => {
          processCalls += 1;
          return { exitCode: 0, stdout: "", stderr: "" };
        },
      },
    });
    expect(result.status).toBe("preserved_unmanaged");
    expect(processCalls).toBe(0);
    expect(await readFile(installed.inspection.target_path, "utf8")).toContain(
      "# changed",
    );
    expect(await lstat(installed.inspection.ownership_path)).toBeDefined();
  });

  it("detects races before installer execution and after a successful process exit", async () => {
    const before = await makeRepository();
    const beforeInspection = await inspectHook(before);
    let beforeProcessCalls = 0;
    await expect(
      installHook(before, {
        lifecycle: {
          checkpoint: async (point) => {
            if (point === "before-install-reinspection")
              await writeFile(
                beforeInspection.target_path,
                "#!/bin/sh\necho raced\n",
              );
          },
        },
        process: {
          execute: async () => {
            beforeProcessCalls += 1;
            return { exitCode: 0, stdout: "", stderr: "" };
          },
        },
      }),
    ).rejects.toMatchObject({ diagnostic: { code: "hook-target-race" } });
    expect(beforeProcessCalls).toBe(0);
    expect(await readFile(beforeInspection.target_path, "utf8")).toContain(
      "raced",
    );

    const after = await makeRepository();
    const afterInspection = await inspectHook(after);
    await expect(
      installHook(after, {
        process: {
          execute: async () => {
            await writeFile(
              afterInspection.target_path,
              "#!/bin/sh\necho competitor\n",
            );
            return { exitCode: 0, stdout: "", stderr: "" };
          },
        },
      }),
    ).rejects.toMatchObject({
      diagnostic: { code: "hook-target-race" },
    });
    expect(await readFile(afterInspection.target_path, "utf8")).toContain(
      "competitor",
    );
  });

  it("rejects a symlinked ownership runtime path without writing through it", async () => {
    const root = await makeRepository();
    const inspection = await inspectHook(root);
    const outside = resolve(
      dirname(root),
      `${root.split("/").pop()}-ownership-outside`,
    );
    temporaryRoots.push(outside);
    await mkdir(outside);
    await symlink(outside, dirname(inspection.ownership_path));
    await expect(
      installHook(root, {
        process: {
          execute: async () => ({
            exitCode: 0,
            stdout: "pre-commit 4.0.1\n",
            stderr: "",
          }),
        },
      }),
    ).rejects.toMatchObject({
      diagnostic: { code: "unsafe-hook-ownership-path" },
    });
    await expect(
      lstat(resolve(outside, "pre-commit-ownership.json")),
    ).rejects.toThrow();
  });

  it("fails closed when the ownership runtime becomes a symlink after inspection", async () => {
    const root = await makeRepository();
    const inspection = await inspectHook(root);
    const outside = resolve(
      dirname(root),
      `${root.split("/").pop()}-runtime-race`,
    );
    temporaryRoots.push(outside);
    await mkdir(outside);
    let raced = false;
    await expect(
      installHook(root, {
        fileSystem: {
          ...hookNodeFileSystem,
          checkpoint: async (point, path) => {
            await hookNodeFileSystem.checkpoint(point, path);
            if (!raced && point === "before-ownership-temp-open") {
              raced = true;
              await rm(dirname(inspection.ownership_path), {
                recursive: true,
                force: true,
              });
              await symlink(outside, dirname(inspection.ownership_path));
            }
          },
        },
        process: {
          execute: async () => ({
            exitCode: 0,
            stdout: "pre-commit 4.0.1\n",
            stderr: "",
          }),
        },
      }),
    ).rejects.toMatchObject({
      diagnostic: { code: "unsafe-hook-ownership-path" },
    });
    expect(raced).toBe(true);
    expect(await readdir(outside)).toEqual([]);
    await expect(lstat(inspection.target_path)).rejects.toThrow();
  });

  it("preserves managed hook bytes when the ownership marker becomes a symlink or races", async () => {
    const root = await makeRepository();
    const initial = await inspectHook(root);
    const installed = await installHook(root, {
      process: {
        execute: async () => ({
          exitCode: 0,
          stdout: "pre-commit 4.0.1\n",
          stderr: "",
        }),
      },
    });
    const saved = `${installed.inspection.ownership_path}.saved`;
    await rename(installed.inspection.ownership_path, saved);
    await symlink(saved, installed.inspection.ownership_path);
    expect((await inspectHook(root)).classification).toBe("unmanaged");
    let processCalls = 0;
    expect(
      await uninstallHook(root, {
        process: {
          execute: async () => {
            processCalls += 1;
            return { exitCode: 0, stdout: "", stderr: "" };
          },
        },
      }),
    ).toMatchObject({ status: "preserved_unmanaged" });
    expect(processCalls).toBe(0);
    expect(await readFile(initial.target_path, "utf8")).toBe(FRAMEWORK_HOOK);

    await unlink(installed.inspection.ownership_path);
    await rename(saved, installed.inspection.ownership_path);
    await expect(
      uninstallHook(root, {
        lifecycle: {
          checkpoint: async (point) => {
            if (point === "before-uninstall-reinspection")
              await writeFile(installed.inspection.ownership_path, "{}\n");
          },
        },
        process: {
          execute: async () => {
            processCalls += 1;
            return { exitCode: 0, stdout: "", stderr: "" };
          },
        },
      }),
    ).rejects.toMatchObject({ diagnostic: { code: "hook-target-race" } });
    expect(processCalls).toBe(0);
    expect(await readFile(initial.target_path, "utf8")).toBe(FRAMEWORK_HOOK);
  });

  it("creates the exact hook itself after availability succeeds", async () => {
    const root = await makeRepository();
    const result = await installHook(root, {
      process: {
        execute: async () => ({
          exitCode: 0,
          stdout: "pre-commit 4.0.1\n",
          stderr: "",
        }),
      },
    });
    expect(result.inspection.classification).toBe("managed");
    expect(await readFile(result.inspection.target_path, "utf8")).toBe(
      FRAMEWORK_HOOK,
    );
  });

  it("removes its exact linked inode when the first post-link target read fails", async () => {
    const root = await makeRepository();
    const initial = await inspectHook(root);
    let failedTargetRead = false;
    const fileSystem = {
      ...hookNodeFileSystem,
      readFile: async (path: string, encoding?: BufferEncoding) => {
        if (!failedTargetRead && path === initial.target_path) {
          failedTargetRead = true;
          throw new Error("injected first post-link target read failure");
        }
        return hookNodeFileSystem.readFile(path, encoding);
      },
    };
    const process = {
      execute: async () => ({
        exitCode: 0,
        stdout: "pre-commit 4.0.1\n",
        stderr: "",
      }),
    };

    await expect(
      installHook(root, { fileSystem, process }),
    ).rejects.toMatchObject({ diagnostic: { code: "hook-target-unreadable" } });

    expect(failedTargetRead).toBe(true);
    expect((await inspectHook(root)).classification).toBe("absent");
    expect(
      (await readdir(dirname(initial.target_path))).filter((name) =>
        name.startsWith("pre-commit.coffee-chat-"),
      ),
    ).toEqual([]);
    const retried = await installHook(root, { process });
    expect(retried.inspection.classification).toBe("managed");
  });

  it("removes its exact linked inode when the first post-link temporary read fails", async () => {
    const root = await makeRepository();
    const initial = await inspectHook(root);
    let failedTemporaryRead = false;
    const fileSystem = {
      ...hookNodeFileSystem,
      readFile: async (path: string, encoding?: BufferEncoding) => {
        if (
          !failedTemporaryRead &&
          path.startsWith(`${initial.target_path}.coffee-chat-`) &&
          path.endsWith(".tmp")
        ) {
          failedTemporaryRead = true;
          throw new Error("injected first post-link temporary read failure");
        }
        return hookNodeFileSystem.readFile(path, encoding);
      },
    };
    const process = {
      execute: async () => ({
        exitCode: 0,
        stdout: "pre-commit 4.0.1\n",
        stderr: "",
      }),
    };

    await expect(
      installHook(root, { fileSystem, process }),
    ).rejects.toMatchObject({ diagnostic: { code: "hook-target-unreadable" } });

    expect(failedTemporaryRead).toBe(true);
    expect((await inspectHook(root)).classification).toBe("absent");
    expect(
      (await readdir(dirname(initial.target_path))).filter((name) =>
        name.startsWith("pre-commit.coffee-chat-"),
      ),
    ).toEqual([]);
    const retried = await installHook(root, { process });
    expect(retried.inspection.classification).toBe("managed");
  });

  it("preserves a replacement that appears during failed-install cleanup", async () => {
    const root = await makeRepository();
    const initial = await inspectHook(root);
    const replacement = "#!/bin/sh\necho cleanup-competitor\n";
    let failedTargetRead = false;
    let replacedAtCleanup = false;
    const fileSystem = {
      ...hookNodeFileSystem,
      readFile: async (path: string, encoding?: BufferEncoding) => {
        if (!failedTargetRead && path === initial.target_path) {
          failedTargetRead = true;
          throw new Error("injected first post-link target read failure");
        }
        return hookNodeFileSystem.readFile(path, encoding);
      },
      checkpoint: async (
        point: Parameters<typeof hookNodeFileSystem.checkpoint>[0],
        path: string,
      ) => {
        await hookNodeFileSystem.checkpoint(point, path);
        if (
          !replacedAtCleanup &&
          point === "before-owned-hook-remove" &&
          path === initial.target_path
        ) {
          replacedAtCleanup = true;
          await unlink(initial.target_path);
          await writeFile(initial.target_path, replacement, { mode: 0o755 });
        }
      },
    };

    await expect(
      installHook(root, {
        fileSystem,
        process: {
          execute: async () => ({
            exitCode: 0,
            stdout: "pre-commit 4.0.1\n",
            stderr: "",
          }),
        },
      }),
    ).rejects.toMatchObject({
      diagnostic: { code: "hook-target-unreadable" },
    });

    expect(failedTargetRead).toBe(true);
    expect(replacedAtCleanup).toBe(true);
    expect(await readFile(initial.target_path, "utf8")).toBe(replacement);
    expect((await inspectHook(root)).classification).toBe("unmanaged");
  });

  it("preserves an unowned hook that appears at the exclusive-create boundary", async () => {
    const root = await makeRepository();
    const initial = await inspectHook(root);
    const competitor = "#!/bin/sh\necho competitor\n";
    let raced = false;
    await expect(
      installHook(root, {
        fileSystem: {
          ...hookNodeFileSystem,
          checkpoint: async (point, path) => {
            await hookNodeFileSystem.checkpoint(point, path);
            if (!raced && point === "before-owned-hook-create") {
              raced = true;
              await writeFile(initial.target_path, competitor, { mode: 0o755 });
            }
          },
        },
        process: {
          execute: async () => ({
            exitCode: 0,
            stdout: "pre-commit 4.0.1\n",
            stderr: "",
          }),
        },
      }),
    ).rejects.toMatchObject({ diagnostic: { code: "hook-target-race" } });
    expect(raced).toBe(true);
    expect(await readFile(initial.target_path, "utf8")).toBe(competitor);
  });

  it("preserves an unowned replacement at the owned-remove boundary", async () => {
    const root = await makeRepository();
    const installed = await installHook(root, {
      process: {
        execute: async () => ({
          exitCode: 0,
          stdout: "pre-commit 4.0.1\n",
          stderr: "",
        }),
      },
    });
    const competitor = "#!/bin/sh\necho replacement\n";
    let raced = false;
    await expect(
      uninstallHook(root, {
        fileSystem: {
          ...hookNodeFileSystem,
          checkpoint: async (point, path) => {
            await hookNodeFileSystem.checkpoint(point, path);
            if (!raced && point === "before-owned-hook-remove") {
              raced = true;
              await writeFile(installed.inspection.target_path, competitor);
            }
          },
        },
      }),
    ).rejects.toMatchObject({ diagnostic: { code: "hook-target-race" } });
    expect(raced).toBe(true);
    expect(await readFile(installed.inspection.target_path, "utf8")).toBe(
      competitor,
    );
  });

  it("detects an intermediate same-path rewrite even when expected bytes are restored", async () => {
    const root = await makeRepository();
    const installed = await installHook(root, {
      process: {
        execute: async () => ({
          exitCode: 0,
          stdout: "pre-commit 4.0.1\n",
          stderr: "",
        }),
      },
    });
    let raced = false;
    await expect(
      uninstallHook(root, {
        fileSystem: {
          ...hookNodeFileSystem,
          checkpoint: async (point, path) => {
            await hookNodeFileSystem.checkpoint(point, path);
            if (!raced && point === "before-owned-hook-remove") {
              raced = true;
              await writeFile(
                installed.inspection.target_path,
                "#!/bin/sh\necho intermediate\n",
              );
              await writeFile(installed.inspection.target_path, FRAMEWORK_HOOK);
            }
          },
        },
      }),
    ).rejects.toMatchObject({ diagnostic: { code: "hook-target-race" } });
    expect(raced).toBe(true);
    expect(await readFile(installed.inspection.target_path, "utf8")).toBe(
      FRAMEWORK_HOOK,
    );
  });

  it("recovers an exact stale ownership marker on a second uninstall", async () => {
    const root = await makeRepository();
    const installed = await installHook(root, {
      process: {
        execute: async () => ({
          exitCode: 0,
          stdout: "pre-commit 4.0.1\n",
          stderr: "",
        }),
      },
    });
    let failedOnce = false;
    await expect(
      uninstallHook(root, {
        fileSystem: {
          ...hookNodeFileSystem,
          checkpoint: async (point, path) => {
            await hookNodeFileSystem.checkpoint(point, path);
            if (!failedOnce && point === "before-ownership-remove") {
              failedOnce = true;
              throw new Error("injected ownership removal failure");
            }
          },
        },
      }),
    ).rejects.toMatchObject({
      diagnostic: { code: "unsafe-hook-ownership-path" },
    });
    await expect(lstat(installed.inspection.target_path)).rejects.toThrow();
    expect(await lstat(installed.inspection.ownership_path)).toBeDefined();

    const recovered = await uninstallHook(root);
    expect(recovered.status).toBe("already_absent");
    await expect(lstat(installed.inspection.ownership_path)).rejects.toThrow();
  });
});
