import { execFile } from "node:child_process";
import { randomUUID } from "node:crypto";
import type { Stats } from "node:fs";
import {
  chmod,
  lstat,
  mkdir,
  open,
  readFile,
  realpath,
  rename,
  rm,
  unlink,
  writeFile,
} from "node:fs/promises";
import { dirname, relative, resolve, sep } from "node:path";
import { promisify } from "node:util";
import { UnableToComplete } from "./contracts.ts";
import { canonicalizeJson } from "./generate.ts";
import { sha256 } from "./knowledge.ts";

const execFileAsync = promisify(execFile);
const FRAMEWORK_URL_MARKER =
  "# File generated by pre-commit: https://pre-commit.com";
const FRAMEWORK_ID_MARKER = "# ID: 138fd403232d2ddd5efb44317e38bf03";
const OWNERSHIP_VERSION = "1.0.0";
const MINIMAL_FRAMEWORK_HOOK = `#!/usr/bin/env bash
${FRAMEWORK_URL_MARKER}
${FRAMEWORK_ID_MARKER}
exec pre-commit hook-impl --hook-type=pre-commit --hook-dir "$(dirname "$0")" -- "$@"
`;
const NATIVE_FRAMEWORK_HOOK = new RegExp(
  String.raw`^#!/usr/bin/env bash\n# File generated by pre-commit: https://pre-commit\.com\n# ID: 138fd403232d2ddd5efb44317e38bf03\n\n# start templated\nINSTALL_PYTHON=[^\r\n]+\nARGS=\(hook-impl --config=[^\r\n)]+ --hook-type=pre-commit\)\n# end templated\n\nHERE="\$\(cd "\$\(dirname "\$0"\)" && pwd\)"\nARGS\+=\(--hook-dir "\$HERE" -- "\$@"\)\n\nif \[ -x "\$INSTALL_PYTHON" \]; then\n    exec "\$INSTALL_PYTHON" -mpre_commit "\$\{ARGS\[@\]\}"\nelif command -v pre-commit > /dev/null; then\n    exec pre-commit "\$\{ARGS\[@\]\}"\nelse\n    echo '` +
    "`pre-commit` not found\\.  Did you forget to activate your virtualenv\\?'" +
    String.raw`\n    exit 1\nfi\n$`,
);

type ProcessRequest = {
  cwd: string;
  command: string;
  args: string[];
  env?: Record<string, string>;
};

type ProcessResult = { exitCode: number; stdout: string; stderr: string };

export type ProcessExecutor = {
  execute(request: ProcessRequest): Promise<ProcessResult>;
};

export type GitExecutor = {
  execute(root: string, args: string[]): Promise<ProcessResult>;
};

export type HookLifecycle = {
  checkpoint(
    point: "before-install-reinspection" | "before-uninstall-reinspection",
  ): Promise<void>;
};

export type HookFileSystemPoint =
  | "before-ownership-read"
  | "before-ownership-temp-open"
  | "before-ownership-rename"
  | "before-ownership-remove";

type HookFileHandle = {
  writeFile(bytes: string | Buffer): Promise<void>;
  sync(): Promise<void>;
  close(): Promise<void>;
};

export type HookFileSystem = {
  checkpoint(point: HookFileSystemPoint, path: string): Promise<void>;
  lstat(path: string): Promise<Stats>;
  readFile(path: string, encoding?: BufferEncoding): Promise<Buffer | string>;
  realpath(path: string): Promise<string>;
  mkdir(path: string, options?: { recursive?: boolean }): Promise<unknown>;
  open(path: string, flags: string, mode?: number): Promise<HookFileHandle>;
  rename(from: string, to: string): Promise<void>;
  chmod(path: string, mode: number): Promise<void>;
  unlink(path: string): Promise<void>;
  rm(
    path: string,
    options?: { recursive?: boolean; force?: boolean },
  ): Promise<void>;
};

export const hookNodeFileSystem: HookFileSystem = {
  checkpoint: async () => undefined,
  lstat,
  readFile,
  realpath,
  mkdir,
  open: async (path, flags, mode) => open(path, flags, mode),
  rename,
  chmod,
  unlink,
  rm,
};

export type HookDependencies = {
  git?: GitExecutor;
  process?: ProcessExecutor;
  lifecycle?: HookLifecycle;
  fileSystem?: HookFileSystem;
};

export type HookFingerprint =
  | { state: "absent" }
  | {
      state: "file";
      digest: string;
      mode: number;
      size: number;
      device: number;
      inode: number;
    }
  | {
      state: "unsafe";
      kind: "symlink" | "directory" | "other";
      device: number;
      inode: number;
    };

export type HookInspection = {
  classification: "absent" | "managed" | "unmanaged";
  target_path: string;
  ownership_path: string;
  git_common_dir: string;
  fingerprint: HookFingerprint;
};

export type HookInstallResult = {
  status: "installed";
  inspection: HookInspection & { classification: "managed" };
};

export type HookUninstallResult = {
  status: "uninstalled" | "already_absent" | "preserved_unmanaged";
  inspection: HookInspection;
};

type Ownership = {
  schema_version: "1.0.0";
  owner: "coffee-chat";
  hook_path: string;
  hook_digest: string;
};

function failure(code: string, message: string): UnableToComplete {
  return new UnableToComplete({ code, path: ".", message });
}

const defaultGit: GitExecutor = {
  async execute(root, args) {
    try {
      const result = await execFileAsync("git", args, {
        cwd: root,
        encoding: "utf8",
        maxBuffer: 16 * 1024 * 1024,
      });
      return { exitCode: 0, stdout: result.stdout, stderr: result.stderr };
    } catch (error) {
      const result = error as {
        code?: number;
        stdout?: string;
        stderr?: string;
      };
      return {
        exitCode: typeof result.code === "number" ? result.code : 2,
        stdout: result.stdout ?? "",
        stderr: result.stderr ?? "",
      };
    }
  },
};

const defaultProcess: ProcessExecutor = {
  async execute(request) {
    try {
      const result = await execFileAsync(request.command, request.args, {
        cwd: request.cwd,
        encoding: "utf8",
        maxBuffer: 16 * 1024 * 1024,
        ...(request.env
          ? { env: { ...process.env, ...request.env } as NodeJS.ProcessEnv }
          : {}),
      });
      return { exitCode: 0, stdout: result.stdout, stderr: result.stderr };
    } catch (error) {
      const result = error as {
        code?: number;
        stdout?: string;
        stderr?: string;
      };
      return {
        exitCode: typeof result.code === "number" ? result.code : 2,
        stdout: result.stdout ?? "",
        stderr: result.stderr ?? "",
      };
    }
  },
};

const defaultLifecycle: HookLifecycle = { checkpoint: async () => undefined };

function dependencies(overrides: HookDependencies): Required<HookDependencies> {
  return {
    git: overrides.git ?? defaultGit,
    process: overrides.process ?? defaultProcess,
    lifecycle: overrides.lifecycle ?? defaultLifecycle,
    fileSystem: overrides.fileSystem ?? hookNodeFileSystem,
  };
}

async function requiredGit(
  git: GitExecutor,
  root: string,
  args: string[],
): Promise<string> {
  const result = await git.execute(root, args);
  if (result.exitCode !== 0 || result.stdout.trim().length === 0)
    throw failure(
      "hook-path-unavailable",
      "The repository hook path could not be resolved safely.",
    );
  return result.stdout.trim();
}

function isWithin(parent: string, child: string): boolean {
  const fromParent = relative(parent, child);
  return (
    fromParent === "" ||
    (fromParent !== ".." && !fromParent.startsWith(`..${sep}`))
  );
}

async function fingerprint(
  targetPath: string,
  fileSystem: HookFileSystem,
): Promise<HookFingerprint> {
  try {
    const status = await fileSystem.lstat(targetPath);
    if (status.isSymbolicLink()) {
      return {
        state: "unsafe",
        kind: "symlink",
        device: status.dev,
        inode: status.ino,
      };
    }
    if (!status.isFile()) {
      return {
        state: "unsafe",
        kind: status.isDirectory() ? "directory" : "other",
        device: status.dev,
        inode: status.ino,
      };
    }
    return {
      state: "file",
      digest: sha256((await fileSystem.readFile(targetPath)) as Buffer),
      mode: status.mode & 0o7777,
      size: status.size,
      device: status.dev,
      inode: status.ino,
    };
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT")
      return { state: "absent" };
    throw failure(
      "hook-target-unreadable",
      "The pre-commit target could not be inspected safely.",
    );
  }
}

function frameworkManaged(bytes: Buffer): boolean {
  const text = bytes.toString("utf8");
  return text === MINIMAL_FRAMEWORK_HOOK || NATIVE_FRAMEWORK_HOOK.test(text);
}

async function readOwnership(
  path: string,
  fileSystem: HookFileSystem,
): Promise<Ownership | undefined> {
  try {
    const before = await fileSystem.lstat(path);
    if (before.isSymbolicLink() || !before.isFile()) return undefined;
    await fileSystem.checkpoint("before-ownership-read", path);
    const bytes = (await fileSystem.readFile(path)) as Buffer;
    const after = await fileSystem.lstat(path);
    if (
      after.isSymbolicLink() ||
      !after.isFile() ||
      before.dev !== after.dev ||
      before.ino !== after.ino ||
      before.size !== after.size
    )
      return undefined;
    const value = JSON.parse(bytes.toString("utf8")) as Partial<Ownership>;
    if (
      value.schema_version === OWNERSHIP_VERSION &&
      value.owner === "coffee-chat" &&
      typeof value.hook_path === "string" &&
      /^sha256:[a-f0-9]{64}$/.test(value.hook_digest ?? "")
    )
      return value as Ownership;
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== "ENOENT") return undefined;
  }
  return undefined;
}

async function ownershipPathIsSafe(
  commonDir: string,
  ownershipPath: string,
  fileSystem: HookFileSystem,
): Promise<boolean> {
  const runtimeDirectory = dirname(ownershipPath);
  try {
    const directoryStatus = await fileSystem.lstat(runtimeDirectory);
    if (directoryStatus.isSymbolicLink() || !directoryStatus.isDirectory())
      return false;
    const resolvedDirectory = await fileSystem.realpath(runtimeDirectory);
    if (!isWithin(commonDir, resolvedDirectory)) return false;
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") return true;
    return false;
  }
  try {
    const ownershipStatus = await fileSystem.lstat(ownershipPath);
    return ownershipStatus.isFile() && !ownershipStatus.isSymbolicLink();
  } catch (error) {
    return (error as NodeJS.ErrnoException).code === "ENOENT";
  }
}

export async function inspectHook(
  root: string,
  overrides: HookDependencies = {},
): Promise<HookInspection> {
  const { git, fileSystem } = dependencies(overrides);
  const configured = await git.execute(root, [
    "config",
    "--show-origin",
    "--get",
    "core.hooksPath",
  ]);
  if (configured.exitCode === 0 && configured.stdout.trim().length > 0) {
    throw failure(
      "configured-hooks-path",
      "Coffee Chat v1 does not install into a configured core.hooksPath.",
    );
  }
  if (configured.exitCode !== 0 && configured.exitCode !== 1) {
    throw failure(
      "hook-path-unavailable",
      "Git hook configuration could not be inspected safely.",
    );
  }

  const [commonRaw, targetRaw] = await Promise.all([
    requiredGit(git, root, ["rev-parse", "--git-common-dir"]),
    requiredGit(git, root, ["rev-parse", "--git-path", "hooks/pre-commit"]),
  ]);
  let commonDir: string;
  try {
    commonDir = await fileSystem.realpath(resolve(root, commonRaw));
  } catch {
    throw failure(
      "hook-path-unavailable",
      "The repository Git directory could not be resolved safely.",
    );
  }
  const targetPath = resolve(root, targetRaw);
  const hooksParent = dirname(targetPath);
  let resolvedParent: string;
  try {
    resolvedParent = await fileSystem.realpath(hooksParent);
  } catch {
    throw failure(
      "hook-path-unavailable",
      "The repository hooks directory could not be resolved safely.",
    );
  }
  if (!isWithin(commonDir, resolvedParent)) {
    throw failure(
      "unsafe-hook-path",
      "The resolved pre-commit target is outside the repository Git directory.",
    );
  }
  const ownershipPath = resolve(
    commonDir,
    "coffee-chat",
    "pre-commit-ownership.json",
  );
  const targetFingerprint = await fingerprint(targetPath, fileSystem);
  const ownershipSafe = await ownershipPathIsSafe(
    commonDir,
    ownershipPath,
    fileSystem,
  );
  if (!ownershipSafe && targetFingerprint.state === "absent") {
    throw failure(
      "unsafe-hook-ownership-path",
      "Coffee Chat hook ownership state is not a safe repository-local file.",
    );
  }
  if (targetFingerprint.state === "absent") {
    return {
      classification: "absent",
      target_path: targetPath,
      ownership_path: ownershipPath,
      git_common_dir: commonDir,
      fingerprint: targetFingerprint,
    };
  }
  let classification: "managed" | "unmanaged" = "unmanaged";
  if (targetFingerprint.state === "file" && ownershipSafe) {
    const [bytes, ownership] = await Promise.all([
      fileSystem.readFile(targetPath) as Promise<Buffer>,
      readOwnership(ownershipPath, fileSystem),
    ]);
    if (
      frameworkManaged(bytes) &&
      ownership?.hook_path === targetPath &&
      ownership.hook_digest === targetFingerprint.digest
    )
      classification = "managed";
  }
  return {
    classification,
    target_path: targetPath,
    ownership_path: ownershipPath,
    git_common_dir: commonDir,
    fingerprint: targetFingerprint,
  };
}

function sameInspection(left: HookInspection, right: HookInspection): boolean {
  return canonicalizeJson(left as never) === canonicalizeJson(right as never);
}

async function writeOwnership(
  inspection: HookInspection,
  digest: string,
  fileSystem: HookFileSystem,
): Promise<void> {
  if (
    !(await ownershipPathIsSafe(
      inspection.git_common_dir,
      inspection.ownership_path,
      fileSystem,
    ))
  ) {
    throw failure(
      "unsafe-hook-ownership-path",
      "Coffee Chat hook ownership state is not a safe repository-local file.",
    );
  }
  const ownership: Ownership = {
    schema_version: "1.0.0",
    owner: "coffee-chat",
    hook_path: inspection.target_path,
    hook_digest: digest,
  };
  const bytes = `${JSON.stringify(ownership, null, 2)}\n`;
  await fileSystem.mkdir(dirname(inspection.ownership_path), {
    recursive: true,
  });
  await fileSystem.checkpoint(
    "before-ownership-temp-open",
    inspection.ownership_path,
  );
  if (
    !(await ownershipPathIsSafe(
      inspection.git_common_dir,
      inspection.ownership_path,
      fileSystem,
    ))
  )
    throw failure(
      "unsafe-hook-ownership-path",
      "Coffee Chat hook ownership state changed before its exclusive write.",
    );
  const temporary = `${inspection.ownership_path}.tmp-${randomUUID()}`;
  const handle = await fileSystem.open(temporary, "wx", 0o600);
  try {
    await handle.writeFile(bytes);
    await handle.sync();
  } finally {
    await handle.close();
  }
  await fileSystem.checkpoint(
    "before-ownership-rename",
    inspection.ownership_path,
  );
  if (
    !(await ownershipPathIsSafe(
      inspection.git_common_dir,
      inspection.ownership_path,
      fileSystem,
    ))
  )
    throw failure(
      "unsafe-hook-ownership-path",
      "Coffee Chat hook ownership state changed before its atomic rename.",
    );
  const temporaryStatus = await fileSystem.lstat(temporary);
  if (temporaryStatus.isSymbolicLink() || !temporaryStatus.isFile())
    throw failure(
      "unsafe-hook-ownership-path",
      "Coffee Chat ownership temporary is not a regular exclusive file.",
    );
  await fileSystem.rename(temporary, inspection.ownership_path);
  await fileSystem.chmod(inspection.ownership_path, 0o600);
  const verified = await readOwnership(inspection.ownership_path, fileSystem);
  if (
    verified?.hook_path !== inspection.target_path ||
    verified.hook_digest !== digest
  )
    throw failure(
      "unsafe-hook-ownership-path",
      "Coffee Chat hook ownership bytes changed during verification.",
    );
}

async function removeOwnership(
  inspection: HookInspection,
  fileSystem: HookFileSystem,
): Promise<void> {
  const ownership = await readOwnership(inspection.ownership_path, fileSystem);
  if (
    ownership?.hook_path !== inspection.target_path ||
    !(await ownershipPathIsSafe(
      inspection.git_common_dir,
      inspection.ownership_path,
      fileSystem,
    ))
  )
    throw failure(
      "unsafe-hook-ownership-path",
      "Coffee Chat ownership runtime no longer matches the inspected target.",
    );
  await fileSystem.checkpoint(
    "before-ownership-remove",
    inspection.ownership_path,
  );
  const rechecked = await readOwnership(inspection.ownership_path, fileSystem);
  if (!sameJsonOwnership(ownership, rechecked))
    throw failure(
      "hook-target-race",
      "Coffee Chat ownership bytes changed before removal and were preserved.",
    );
  await fileSystem.unlink(inspection.ownership_path);
  await fileSystem
    .rm(dirname(inspection.ownership_path), { recursive: false })
    .catch(() => undefined);
}

function sameJsonOwnership(
  left: Ownership | undefined,
  right: Ownership | undefined,
): boolean {
  return Boolean(
    left &&
      right &&
      canonicalizeJson(left as never) === canonicalizeJson(right as never),
  );
}

export async function installHook(
  root: string,
  overrides: HookDependencies = {},
): Promise<HookInstallResult> {
  const deps = dependencies(overrides);
  const initial = await inspectHook(root, deps);
  if (initial.classification === "unmanaged")
    throw failure(
      "unmanaged-pre-commit-hook",
      "An unmanaged pre-commit hook is present and was preserved.",
    );
  await deps.lifecycle.checkpoint("before-install-reinspection");
  const immediate = await inspectHook(root, deps);
  if (!sameInspection(initial, immediate)) {
    throw failure(
      "hook-target-race",
      "The pre-commit target changed during inspection and was preserved.",
    );
  }
  const processResult = await deps.process.execute({
    cwd: root,
    command: "pre-commit",
    args: ["install", "--hook-type", "pre-commit"],
  });
  if (processResult.exitCode !== 0) {
    throw failure(
      "hook-install-failed",
      "The native pre-commit installer did not complete successfully.",
    );
  }
  const postFingerprint = await fingerprint(
    initial.target_path,
    deps.fileSystem,
  );
  if (postFingerprint.state !== "file") {
    throw failure(
      "hook-install-verification-failed",
      "The native installer did not create a verifiable framework hook.",
    );
  }
  const bytes = (await deps.fileSystem.readFile(initial.target_path)) as Buffer;
  if (!frameworkManaged(bytes)) {
    throw failure(
      "hook-install-verification-failed",
      "The installed pre-commit target is not the expected framework-managed hook.",
    );
  }
  await writeOwnership(initial, postFingerprint.digest, deps.fileSystem);
  const verified = await inspectHook(root, deps);
  if (verified.classification !== "managed") {
    await deps.fileSystem.rm(initial.ownership_path, { force: true });
    throw failure(
      "hook-install-verification-failed",
      "The installed pre-commit target changed before ownership verification.",
    );
  }
  return {
    status: "installed",
    inspection: verified as HookInspection & { classification: "managed" },
  };
}

export async function uninstallHook(
  root: string,
  overrides: HookDependencies = {},
): Promise<HookUninstallResult> {
  const deps = dependencies(overrides);
  const initial = await inspectHook(root, deps);
  if (initial.classification === "unmanaged")
    return { status: "preserved_unmanaged", inspection: initial };
  if (initial.classification === "absent") {
    const ownership = await readOwnership(
      initial.ownership_path,
      deps.fileSystem,
    );
    if (ownership?.hook_path === initial.target_path) {
      await removeOwnership(initial, deps.fileSystem);
    }
    return { status: "already_absent", inspection: initial };
  }
  await deps.lifecycle.checkpoint("before-uninstall-reinspection");
  const immediate = await inspectHook(root, deps);
  if (!sameInspection(initial, immediate)) {
    throw failure(
      "hook-target-race",
      "The pre-commit target changed during inspection and was preserved.",
    );
  }
  const processResult = await deps.process.execute({
    cwd: root,
    command: "pre-commit",
    args: ["uninstall", "--hook-type", "pre-commit"],
  });
  if (processResult.exitCode !== 0)
    throw failure(
      "hook-uninstall-failed",
      "The native pre-commit uninstaller did not complete successfully.",
    );
  const after = await inspectHook(root, deps);
  if (after.classification !== "absent")
    throw failure(
      "hook-uninstall-verification-failed",
      "The pre-commit target was not removed exactly by the native uninstaller.",
    );
  await removeOwnership(initial, deps.fileSystem);
  return { status: "uninstalled", inspection: after };
}
